version: '2'
services:
  mc-server:
    network_mode: host
    restart: always
    build: ./mc-server
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: ddns-route53
    environment:
      - "TZ=America/Los_Angeles"
      - "SCHEDULE=0 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DDNSR53_CREDENTIALS_ACCESSKEYID=${AWS_ACCESS_KEY_ID}"
      - "DDNSR53_CREDENTIALS_SECRETACCESSKEY=${AWS_SECRET_ACCESS_KEY}"
      - "DDNSR53_ROUTE53_HOSTEDZONEID=${HOSTED_ZONE_ID}"
      - "DDNSR53_ROUTE53_RECORDSSET_0_NAME=${RECORD_NAME}"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TYPE=A"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TTL=300"
    restart: always
volumes:
  serverfiles:
  servercache:
